export { default as ForgotPassword } from './ForgotPassword';
export { default as NotFount } from './NotFount';
export * from  './Private/Categories/form';
export * from'./Private/Categories';
export * from './Private/Products/ControlPanel';
export * from './Private/Products/form';
export * from './Private/Products';
export * from './Private/Settings';
export * from './Private/clients/form';
export * from './Private/clients';
export * from './Private';
export * from './Private/orders/form';
export * from './Private/orders';
export * from './Signin';
export { default as Signup } from './Signup';
